apiVersion: v1
kind: Service
metadata:
  name: {{ include "previa.mainName" . }}
  labels:
    {{- include "previa.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
spec:
  type: {{ .Values.main.service.type }}
  ports:
    - name: http
      port: {{ .Values.main.service.port }}
      targetPort: http
  selector:
    {{- include "previa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main
