{{- if .Values.kubernetesPlugin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "previa.pluginName" . }}
  labels:
    {{- include "previa.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-plugin
spec:
  type: {{ .Values.kubernetesPlugin.service.type }}
  ports:
    - name: http
      port: {{ .Values.kubernetesPlugin.service.port }}
      targetPort: http
  selector:
    {{- include "previa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-plugin
{{- end }}
