{{- if and .Values.kubernetesPlugin.enabled .Values.kubernetesPlugin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "previa.pluginServiceAccountName" . }}
  labels:
    {{- include "previa.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubernetes-plugin
  annotations:
    {{- toYaml .Values.kubernetesPlugin.serviceAccount.annotations | nindent 4 }}
{{- end }}
